library:
  source-dirs: src
tests:
  CSG-Haskell-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSG-Haskell
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- time
- text
- OpenGLRaw
- GLFW-b
- base >= 4.7 && < 5
name: CSG-Haskell
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/CSG-Haskell
license: BSD3
executables:
  CSG-Haskell-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSG-Haskell
description: Please see the README on GitHub at <https://github.com/githubuser/CSG-Haskell#readme>
